name: Check and generate PURL Type Docs and Index

on:
  push:
    paths:
      - "schemes/*.json"
      - "schemas/*.json"
      - "etc/"
    branches:
      - main
  workflow_dispatch:
# All permissions should be specified at the job level
permissions: { }

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: make conf

      - name: Validate code and data formats
        run: make check

